CREATE VIEW VW_USUARIOS_REPORTES AS
	SELECT
		U.NombreUsuario AS USERNAME,
		U.IdTipoUsuario AS ROL,
		COUNT(PFP.FechaEmisión) AS OPERACIONES_PROGRAMACION,
		COUNT(ORA.FechaAdmision) AS OPERACIONES_ADMISION
	FROM USUARIO U
		INNER JOIN OPERACION_FICHAPROGRAMACION PFP ON U.IdUsuario = PFP.IdUsuario
		INNER JOIN OPERACION_REPORTE_ADMISION ORA ON U.IdUsuario = ORA.IdUsuario
	GROUP BY U.IdUsuario, U.NombreUsuario, U.IdTipoUsuario;
GO
