-- RESTRICCIONES CERTIFICADO_MEDICO --
ALTER TABLE CERTIFICADO_MEDICO
ADD CONSTRAINT CHK_Peso_Range CHECK (Peso > 0 AND Peso < 300);

ALTER TABLE CERTIFICADO_MEDICO
ADD CONSTRAINT CHK_Altura_Range CHECK (Altura > 0 AND Altura < 250);
