-- RESTRICCIONES CONTRATO --
ALTER TABLE CONTRATO
ADD CONSTRAINT CHK_FechaInicio_FechaFinal_Contrato CHECK (FechaInicio <= FechaFinal);

ALTER TABLE CONTRATO
ADD CONSTRAINT CHK_IdTipoIdenticacion_Range_Contrato CHECK (IdTipoIdenticacion BETWEEN 0 AND 10);

ALTER TABLE CONTRATO
ADD CONSTRAINT CHK_IdEstado_Contrato CHECK (IdEstado BETWEEN 0 AND 10);