-- RESTRICCIONES TELEFONO --
ALTER TABLE TELEFONO
ADD CONSTRAINT CHK_NumeroTelefono_Length_TELEFONO CHECK (LEN(NumeroTelefono) = 9);

ALTER TABLE TELEFONO
ADD CONSTRAINT CHK_NumeroTelefono_Digits_TELEFONO CHECK (NumeroTelefono NOT LIKE '%[^0-9]%');

ALTER TABLE TELEFONO
ADD CONSTRAINT CHK_InformacionAdicional_Length_TELEFONO CHECK (LEN(InformacionAdicional) <= 15);